### ISSUE TITLE
Json File in assets Folder: First Record is not formatted correct

### ISSUE THREAD

**Issue by hansschenker** [bniedermeyer/json-server-schematics#1]
{ "links": [{ "id": "1", "name": "link": "1" }

should be:

{ "links": [{ "id": "1", "name": "link 1" }

**Comment by bniedermeyer** [comment]
Ah, good catch - thank you! I’ll have a fix out in the next 24 hours.

**Comment by bniedermeyer** [comment]
@hansschenker Can you please point me to the file you're seeing that JSON issue in? I've been looking and can't track it down. 

The only JSON files the schematic creates are the example database: 
```json
{
  "posts": [{ "id": 1, "title": "json-server", "author": "typicode" }],
  "comments": [{ "id": 1, "body": "some comment", "postId": 1 }],
  "profile": { "name": "typicode" }
}
```

The example json-server routes: 
```json
{
  "/api/*": "/$1",
  "/:resource/:id/show": "/:resource/:id",
  "/posts/:category": "/posts?category=:category",
  "/articles\\?id=:id": "/posts/:id"
}
```

and the proxy conf
```json
{
  "/api": {
    "target": "http://localhost:3000/",
    "secure": false
  }
}
```

**Comment by hansschenker** [comment]
Hi Brenden,
thank's a lot for your Json-Server schematics!
It is very helpful to setup it with an Angular App.

Happy and Healthy 2020!
Hans

Am Do., 16. Jan. 2020 um 19:21 Uhr schrieb Brenden Niedermeyer <
notifications@github.com>:

**Comment by bniedermeyer** [comment]
You're welcome, glad it's helping! Is it safe to assume that your problem is fixed?
